name: "GPT Translate Action - Translate any files with OpenAI ChatGPT"
description: "Detects changes in specified file types, translates them using OpenAI API, and commits the translations."
author: "Iman Nemati"
branding:
  icon: "book-open"
  color: "blue"

inputs:
  api_key:
    description: "AI Service API Key"
    required: true
  ai_service:
    description: "AI service provider"
    required: false
    default: "openai"
  ai_model:
    description: "AI model"
    required: false
    default: "gpt-4"
  target_lang:
    description: "Target language for translation (e.g., Persian, Spanish, German, French)"
    required: false
    default: "Persian"
  target_lang_code:
    description: "Target language code. (e.g: fa for Persian, or ru for Russian)"
    required: false
    default: "fa"
  file_exts:
    description: "Comma-separated list of file extensions to translate (e.g., md,json,txt)"
    required: false
    default: "md"
  output_format:
    description: "Pattern for translated filenames. Use {lang} for language and {ext} for extension (e.g., *-{lang}.{ext}, translated_*.{ext})"
    required: false
    default: "*-{lang}.{ext}"
  user_prompt:
    description: "Customized user-prompt to send to AI model."
    required: false
    default: "Translate this text to {TARGET_LANG} while keeping YAML keys, Any html or json markups unchanged:\n{text}"
  system_prompt:
    description: "Customized system-prompt to send to AI model."
    required: false
    default: "You are a translator specializing in software development. Preserve YAML metadata, HTML, and other markuo formats or codes. and also technical terms in general software development DO NOT translate them to target language. Translate the text to {TARGET_LANG}."
  base_branch:
    description: "The base branch to diff against (if not automatically detected)"
    required: false

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    API_KEY: ${{ inputs.api_key }}
    AI_SERVICE: ${{ inputs.ai_service }}
    AI_MODEL: ${{ inputs.ai_model }}
    TARGET_LANG: ${{ inputs.target_lang }}
    TARGET_LANG_CODE: ${{ inputs.target_lang_code }}
    FILE_EXTS: ${{ inputs.file_exts }}
    OUTPUT_FORMAT: ${{ inputs.output_format }}
    BASE_BRANCH: ${{ inputs.base_branch }}