name: "GPT Translate Action - Translate any files with OpenAI ChatGPT"
description: "Detects changes in specified file types, translates them using OpenAI API with optional refinement, and commits the translations."
author: "Iman Nemati"
branding:
  icon: "book-open"
  color: "blue"

inputs:
  api_key:
    description: "OpenAI API Key"
    required: true
  base_url:
    description: "Custom OpenAI API endpoint URL"
    required: false
    default: "https://openrouter.ai/api/v1"
  ai_model:
    description: "OpenAI model to use (e.g., gpt-4, gpt-3.5-turbo)"
    required: false
    default: "gpt-4"
  target_lang:
    description: "Target language (e.g., French, Spanish, German)"
    required: false
    default: "Simplified-Chinese"
  input_files:
    description: "Explicit list of input files to translate (space-separated)"
    required: true
  output_files:
    description: "Output file pattern (e.g., 'docs/cn/**/*.{md,json}')"
    required: true

  system_prompt:
    description: "System prompt to set AI behavior. If provided, the content to translate will be sent as user prompt. Can be text or a file path."
    required: false

  prompt:
    description: "Customized user prompt to send to AI model. Can be text or a file path."
    required: false

  refine_enabled:
    description: "Enable second AI model for refinement after translation"
    required: false
    default: "true"
  refine_ai_model:
    description: "AI model for refinement (uses the same service as primary translation but with a different model)"
    required: false

  refine_system_prompt:
    description: "System prompt for refinement AI model. Can be text or a file path."
    required: false

  refine_prompt:
    description: "User prompt for refinement AI model. Can be text or a file path."
    required: false
  temperature:
    description: "Temperature setting for controlling randomness (0.0 to 1.0)"
    required: false
    default: "0.3"
  refine_temperature:
    description: "Temperature setting for refinement model (0.0 to 1.0)"
    required: false
    default: "0.3"
  base_branch:
    description: "The base branch to diff against (if not automatically detected)"
    required: false
  pr_title:
    description: "Custom PR title (default: 'Add LLM Translations')"
    required: false
    default: "Add LLM Translations"
  batch_size_per_commit:
    description: "Number of files to process in each commit batch (default: 2)"
    required: false
    default: "2"
  batch_size:
    description: "[DEPRECATED: Use batch_size_per_commit instead] Number of files to process in each batch"
    required: false
    default: "20"
  github_token:
    description: "GitHub token for PR creation"
    required: false

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    API_KEY: ${{ inputs.api_key }}
    BASE_URL: ${{ inputs.base_url }}
    AI_MODEL: ${{ inputs.ai_model }}
    TARGET_LANG: ${{ inputs.target_lang }}
    INPUT_FILES: ${{ inputs.input_files }}
    OUTPUT_FILES: ${{ inputs.output_files }}
    SYSTEM_PROMPT: ${{ inputs.system_prompt }}
    PROMPT: ${{ inputs.prompt }}
    REFINE_ENABLED: ${{ inputs.refine_enabled }}
    REFINE_AI_MODEL: ${{ inputs.refine_ai_model }}
    REFINE_SYSTEM_PROMPT: ${{ inputs.refine_system_prompt }}
    REFINE_PROMPT: ${{ inputs.refine_prompt }}
    TEMPERATURE: ${{ inputs.temperature }}
    REFINE_TEMPERATURE: ${{ inputs.refine_temperature }}
    BASE_BRANCH: ${{ inputs.base_branch }}
    PR_TITLE: ${{ inputs.pr_title }}
    BATCH_SIZE_PER_COMMIT: ${{ inputs.batch_size_per_commit }}
    BATCH_SIZE: ${{ inputs.batch_size }}
    GITHUB_TOKEN: ${{ inputs.github_token }}